-- Insert case studies data into the database
INSERT INTO case_studies (
  title, 
  category, 
  industry, 
  summary, 
  impact, 
  icon, 
  image, 
  content,
  tags,
  featured,
  display_order
) VALUES 
(
  'Intelligent Web-Crawler for 100 E-Commerce Webshops',
  'AI & Web Development',
  'E-commerce',
  'Developed an intelligent web crawler for 300+ B2B e-commerce webshops for a toy distributor, automating product, category, price, and inventory data collection with 24/7 efficiency.',
  '100% efficiency in data collection',
  'ShoppingCart',
  '/web-crawler.jpg',
  'Detailed case study about the intelligent web crawler development project that revolutionized data collection for a major toy distributor.',
  ARRAY['Web Crawling', 'AI', 'Data Extraction', 'E-commerce', 'JAVA', 'PHP'],
  true,
  1
),
(
  'Mobile App Development for Gas Bottle Monitoring',
  'App Development',
  'Manufacturing / IoT',
  'Developed a highly-rated iOS and Android mobile app using Flutter for Gastimate Technologies GmbH to monitor and order gas bottles, including UX/UI design and testing.',
  'Highly rated on App Stores',
  'Smartphone',
  '/Mobile App Development for Gas Bottle Monitoring.jpg',
  'Complete mobile app development case study covering the full development lifecycle from design to deployment.',
  ARRAY['Mobile App', 'Flutter', 'iOS', 'Android', 'UX/UI Design', 'IoT'],
  true,
  2
),
(
  'Application Development & Maintenance for Educational Institution',
  'Custom Software Development',
  'Education',
  'Provided ongoing app maintenance and development services for Zaigen GmbH, an educational institution, including application updates and building new modules and admin panels.',
  'High-quality, proactive solutions',
  'GraduationCap',
  '/edu-institute.jpg',
  'Long-term partnership case study showing how we support educational institutions with ongoing development and maintenance services.',
  ARRAY['Custom Software', 'App Maintenance', 'PHP', 'Firewall', 'Education'],
  true,
  3
),
(
  'Custom Software Development & Legacy Application Review for IT Firm',
  'Custom Software Development',
  'IT Services',
  'Performed an in-depth code review and provided support for three critical legacy custom applications for an IT Managed Services Firm, ensuring continuous operations.',
  'Avoided loss of operations',
  'Code',
  '/custom-software.jpg',
  'Critical legacy system modernization project that saved an IT firm from operational disruption.',
  ARRAY['Custom Software', 'Code Review', 'Legacy Systems', 'IT Services'],
  false,
  4
),
(
  'Financial Portals for Gold & Precious Metal Saving Plans',
  'Financial Software Development',
  'Finance',
  'Designed and developed end-to-end customer portals for Geiger Edelmetalle AG, enabling 80k+ German customers to buy/sell gold/silver, manage assets, and view market trends securely.',
  '80K+ German customers served',
  'Building2',
  '/financial-services.jpg',
  'Large-scale financial platform development serving tens of thousands of customers in the precious metals market.',
  ARRAY['Financial Portals', 'Fintech', 'Gold Investment', 'PHP', 'Laravel', 'Vue.js'],
  false,
  5
),
(
  'IoT-Based Security Patrolling System',
  'IoT Solutions',
  'Security & Facilities Management',
  'Developed an intelligent IoT-based security system for Connect Security Solutions, enabling real-time monitoring of security activities from IoT devices and displaying KPIs on a dashboard.',
  'Real-time monitoring of hundreds of locations',
  'Shield',
  '/iot-security.jpg',
  'Comprehensive IoT security solution that transformed how security companies monitor and manage their operations.',
  ARRAY['IoT', 'Security System', 'Real-time Monitoring', 'Dashboard', 'AI'],
  false,
  6
),
(
  'Writeomatic App: Agentic AI Powerhouse for Copywriting',
  'AI & SaaS Development',
  'Marketing & Content Creation',
  'Developed Writeomatic, an AI-powered agentic application for automated copywriting, enabling users to generate high-quality, long-form content, optimize for SEO, and streamline content creation processes.',
  'Revolutionized content creation process',
  'Brain',
  '/Writeomatic-App.jpg',
  'Cutting-edge AI application that leverages agentic AI to revolutionize content creation and copywriting workflows.',
  ARRAY['AI', 'Agentic AI', 'SaaS', 'Copywriting', 'Content Generation', 'SEO Optimization'],
  true,
  7
),
(
  'AI-Powered Viral Reel Creation',
  'AI & Content Marketing',
  'Marketing & Social Media',
  'Leveraged AI to analyze social media trends and audience preferences to create engaging and viral short-form video content (reels), optimizing for maximum reach and impact.',
  'Increased content virality',
  'Camera',
  '/ai-reels.jpg',
  'Innovative AI-driven approach to social media content creation that maximizes viral potential and audience engagement.',
  ARRAY['AI', 'Video Content', 'Social Media Marketing', 'Content Strategy', 'Viral Content'],
  false,
  8
),
(
  'ERP App for Shopify Businesses: Inventory Management',
  'ERP Development',
  'E-commerce',
  'Developed a comprehensive ERP application specifically for Shopify businesses to streamline and automate inventory management, order processing, and other critical business operations.',
  'Improved inventory accuracy',
  'ShoppingCart',
  '/shopify.jpg',
  'Specialized ERP solution designed for Shopify merchants to optimize their inventory management and business processes.',
  ARRAY['ERP', 'Shopify', 'Inventory Management', 'E-commerce', 'Business Automation'],
  false,
  9
);