-- Insert testimonials data
INSERT INTO public.testimonials (client_name, company, position, content, rating, image, impact, featured, active, display_order) VALUES
('Sarah Johnson', 'TechForward Inc.', 'CTO', 'Ähdus Technology transformed our entire development process. Their AI integration expertise helped us reduce development time by 60% while maintaining the highest quality standards.', 5, 'https://images.unsplash.com/photo-1494790108755-2616b612b2e5?w=400&h=400&fit=crop&crop=face', '60% faster development', true, true, 1),
('Michael Chen', 'InnovateLabs', 'VP of Product', 'The team''s deep understanding of both AI and traditional software development made them the perfect partner for our digital transformation journey. Outstanding results.', 5, 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face', '$2M cost savings', true, true, 2),
('Emily Rodriguez', 'StartupX', 'Founder', 'Working with Ähdus was a game-changer. They didn''t just deliver code; they delivered a complete solution that scaled our business from startup to enterprise level.', 5, 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face', '10x user growth', true, true, 3),
('David Kumar', 'MegaCorp', 'Engineering Director', 'Their expertise in industrial IoT and AI helped us modernize our entire manufacturing process. The results exceeded our expectations.', 5, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face', '40% efficiency gain', true, true, 4);

-- Insert additional team members for the about page from WeAreDevelopers page
INSERT INTO public.team_members (name, role, bio, expertise, image, email, linkedin_url, github_url, page_type, active, display_order) VALUES
('Alex Chen', 'Senior Full-Stack Developer', 'Passionate about creating scalable web applications with modern technologies. Experienced in React, Node.js, and cloud platforms.', ARRAY['React', 'Node.js', 'AWS', 'TypeScript'], '/team/team1.jpg', 'alex@ahdus.com', 'https://linkedin.com/in/alexchen', 'https://github.com/alexchen', 'about', true, 1),
('Sarah Kim', 'AI/ML Engineer', 'Specializes in machine learning algorithms and AI model deployment. Expert in Python, TensorFlow, and data science.', ARRAY['Python', 'TensorFlow', 'Machine Learning', 'Data Science'], '/team/team2.jpg', 'sarah@ahdus.com', 'https://linkedin.com/in/sarahkim', 'https://github.com/sarahkim', 'about', true, 2),
('Marcus Johnson', 'DevOps Lead', 'Ensures smooth deployment and infrastructure management. Expert in Docker, Kubernetes, and CI/CD pipelines.', ARRAY['Docker', 'Kubernetes', 'CI/CD', 'Infrastructure'], '/team/team3.jpg', 'marcus@ahdus.com', 'https://linkedin.com/in/marcusjohnson', 'https://github.com/marcusjohnson', 'about', true, 3),
('Elena Rodriguez', 'UI/UX Designer', 'Creates beautiful and intuitive user experiences. Skilled in Figma, user research, and design systems.', ARRAY['UI/UX Design', 'Figma', 'User Research', 'Design Systems'], '/team/team4.jpg', 'elena@ahdus.com', 'https://linkedin.com/in/elenarodriguez', NULL, 'about', true, 4),
('David Park', 'Backend Developer', 'Focuses on server-side development and database optimization. Expert in Python, PostgreSQL, and microservices.', ARRAY['Python', 'PostgreSQL', 'Microservices', 'API Development'], '/team/team5.jpg', 'david@ahdus.com', 'https://linkedin.com/in/davidpark', 'https://github.com/davidpark', 'about', true, 5),
('Lisa Wang', 'Product Manager', 'Drives product strategy and coordinates development efforts. Experienced in agile methodologies and stakeholder management.', ARRAY['Product Strategy', 'Agile', 'Stakeholder Management', 'Analytics'], '/team/team6.jpg', 'lisa@ahdus.com', 'https://linkedin.com/in/lisawang', NULL, 'about', true, 6),
('Tom Mitchell', 'Security Engineer', 'Ensures application security and compliance. Expert in cybersecurity, penetration testing, and security audits.', ARRAY['Cybersecurity', 'Penetration Testing', 'Security Audits', 'Compliance'], '/team/team7.jpg', 'tom@ahdus.com', 'https://linkedin.com/in/tommitchell', 'https://github.com/tommitchell', 'about', true, 7);